import styles from '../styles/Verify.module.css'
import {useState} from 'react';
import Head from 'next/head'
import Navbar from './Navbar'
import loader from '../public/loading.gif'
import Image from 'next/image'
const Verify=()=>{
    const [disp,setDisp]=useState("none")
    const [disp1,setDisp1]=useState("none")
    const [CID,setCID]=useState("")
    const [bill,setBill]=useState({
        PName:"Vivo V11",
        PPrice:"30000",
        IMEI:"IMEI98765",
        email:"",
        Aadhar:"",
        DOM:"20 Aug 2021",
        DOP:"",
        LTS:"29 Sep 2021",
        Servicing:"Not Applicable"
    });
    const handleInput=(e)=>{
        setCID(e.target.value)
    }
    const getStaticProps=async (e)=>{
        setDisp1("block")
        e.preventDefault()
        if(disp!="none") setDisp("none")
        try{
        const res=await fetch(`http://localhost:5000/data`,{
            method:"POST",
            headers:{
                "Content-Type":"application/json",
                "Access-Control-Allow-Origin":"*"
            },
            body:JSON.stringify({"CID":CID})
        })
        const result=await res.json();
        if(result.status>=400) window.alert("Error")
        else{
        console.log(result.data)
        setBill(result.data)
        setDisp1("none")
        setDisp("block")
        }
        }catch(err){
        setDisp("block");
        setDisp1("none")
        console.log(err)
        }
    setDisp1("none")
    }
    return(
        <>
        <Head>
        <title>Block Pay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Block Pay.jpeg" />
      </Head>
         <div className={styles.verify}>
         <Navbar/>
            <div className={styles.head}>Please enter your Product Hash ID</div>
            <input className={styles.input} type="text" name="CID" value={CID.CID} placeholder='Enter Product Hash ID' onChange={handleInput}></input>
            <div className={styles.button} onClick={getStaticProps}>Verify</div>
            <div className={styles.loader} style={{display:disp1}}>
            <Image src={loader} width={150} height={100} alt="Loading..."></Image>
            <div>Loading...</div>
            </div>

            <div className={styles.bill} style={{display:disp}}>
           <div className={styles.data}>
               <div>Product Name</div>
               <div>{bill.PName}</div>
           </div>
           <div className={styles.data}>
               <div>IMEI Number</div>
               <div>{bill.IMEI}</div>
           </div>
           
           <div className={styles.data}>
               <div>Product Price</div>
               <div>{bill.PPrice}</div>
           </div>
           <div className={styles.data}>
               <div>Email of Customer</div>
               <div>{bill.email}</div>
           </div>
           <div className={styles.data}>
               <div>Aadhar Number of Customer</div>
               <div>{bill.Aadhar}</div>
           </div>
           <div className={styles.data}>
               <div>Date of Manufacture</div>
               <div>{bill.DOM}</div>
           </div>
           <div className={styles.data}>
               <div>Date of Purchase</div>
               <div>{bill.DOP}</div>
           </div>
           <div className={styles.data}>
               <div>Last Time Manufacture</div>
               <div>{bill.LTS}</div>
           </div>
           <div className={styles.data}>
               <div>Servicing Details</div>
               <div>{bill.Servicing}</div>
           </div>
  </div>
            </div>

        </>
    )
}
export default Verify;